### ISSUE TITLE
Normal Repos, but bad code!

### ISSUE THREAD

**Issue by yuriibabii** [gitrem2/NormalRepos#1]
Yes I said what I said/

**Comment by gitrem2** [comment]
It was your mistake!

**Comment by gitrem2** [comment]
@UniorDev 
Now u hear me?

**Comment by gitrem2** [comment]
@UniorDev 
Check this out!

**Comment by gitrem2** [comment]
@UniorDev 
Lets add some code to see list perfomance!

**Comment by gitrem2** [comment]
@UniorDev 
Don't know what u about

**Comment by gitrem2** [comment]
@UniorDev 
Just do what u need to do

**Comment by gitrem2** [comment]
@UniorDev 
Forget about me?

**Comment by gitrem2** [comment]
@UniorDev 
I will remember you

**Comment by gitrem2** [comment]
@UniorDev 
From times to times

**Comment by gitrem2** [comment]
Ahahaha
It was only one field ^(
